import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navigation = [
  {
    name: "Login",
    url: "/login",
  },
  {
    name: "Sing Up",
    url: "/singup",
  },
  {
    name: "Home",
    url: "/",
  },
  {
    name: "Profile",
    url: "/profile",
  },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-center">
          {navigation.map((navigate) => (
            <div className="m-2 text-center">
              <Link href={navigate.url}>{navigate.name}</Link>
            </div>
          ))}
        </div>
        {children}
      </body>
    </html>
  );
}
