"use client";

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CartIconSvg, Container } from "@/components/shared";
import Image from "next/image";
import { navigation } from "@/appConfig";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { clsx } from "clsx";

import logo from "@/../../public/images/logo.svg";
import { addHoverPrefix } from "@/utils";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathName = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container className={"m-auto"}>
          <header>
            <div className="flex gap-11 items-center justify-between border-b-2 border-neutral-light-grayish-blue">
              <Image src={logo} alt="logo" />
              <nav className="lg:flex hidden gap-8 grow align-self-start text-neutral-dark-grayish-blue">
                {navigation.map(({ url, name }) => {
                  const isActive = pathName === url;
                  const activeClass = "border-b-4 rounded-sm border-primary";
                  const hoverClass = addHoverPrefix(activeClass);
                  return (
                    <Link
                      className={clsx("py-9", isActive || hoverClass, {
                        [activeClass]: isActive,
                      })}
                      href={url}
                      key={name}
                    >
                      {name}
                    </Link>
                  );
                })}
              </nav>
              <div className="flex gap-8 align-self-end">
                {/* TODO :- change color on hover */}
                <button className="p-2">
                  <CartIconSvg className="fill-neutral-dark-grayish-blue hover:fill-black" />
                </button>
                <button className="rounded-full border-2 hover:border-primary">
                  <Image
                    className="rounded-full"
                    src="/images/image-avatar.png"
                    width="40"
                    height="40"
                    alt="cart icon"
                  />
                </button>
              </div>
            </div>
          </header>
          {children}
        </Container>
      </body>
    </html>
  );
}
